[project]
name = 'Quantum-Computational-Resource-Sharing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.entanglement-based-parallel-processing]
path = 'contracts/entanglement-based-parallel-processing.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-processor-registration]
path = 'contracts/quantum-processor-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-result-verification]
path = 'contracts/quantum-result-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.superposition-computation-allocation]
path = 'contracts/superposition-computation-allocation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
